# Generated by Django 5.1.2 on 2024-12-10 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption_app', '0006_userrelation_accepted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelation',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='related_user',
        ),
        migrations.AddField(
            model_name='userrelation',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_relations_encryption_app', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations_encryption_app', to=settings.AUTH_USER_MODEL),
        ),
    ]
