# Generated by Django 5.1.2 on 2024-11-30 22:53

import two_factor_face_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_face_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaceimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userfaceimage',
            name='image',
            field=models.ImageField(upload_to=two_factor_face_auth.models.content_file_name),
        ),
    ]
